### ISSUE TITLE
Could you provide the geometrically optimized SAM molecular structures?

### ISSUE THREAD

**Issue by Jevon-Du** [Swordshinehjy/ML_perovskite_buired_interface#1]
Hi,

Could you provide the geometrically optimized SAM molecular structures?

Thanks.

**Comment by Swordshinehjy** [comment]
The DFT calculations are the major work for preparing the dataset. Generating the corresponding descriptors requires files containing wave functions, which are large and not readily made public. We have described in detail how to optimize the structures in the manuscript, i.e., at the B3LYP-D3(BJ)/def2-SVP level of theory. The basis set is not large, and if you have the software, it is easy to obtain the results. Also, some of the calculated results will be used in our upcoming work. Please note that we are not professional public dataset maintainers. If you are interested, please apply for cooperation upon reasonable request and the we will share part of the results after internal evaluation.

If you're interested in machine learning about organic semiconductors, you may first try some public datasets that contain geometrical information, such as the Harvard Organic Photovoltaic Dataset (HOPV).

**Comment by Swordshinehjy** [comment]
The DFT calculations are the major work for preparing the dataset. Generating the corresponding descriptors requires files containing wave functions, which are large and not readily made public. We have described in detail how to optimize the structures in the manuscript, i.e., at the B3LYP-D3(BJ)/def2-SVP level of theory. The basis set is not large, and if you have the software, it is easy to obtain the results. Also, some of the calculated results will be used in our upcoming work. Please note that we are not professional public dataset maintainers. If you are interested, please apply for cooperation upon reasonable request and the we will share part of the results after internal evaluation.

If you're interested in machine learning about organic semiconductors, you may first try some public datasets that contain geometrical information, such as the Harvard Organic Photovoltaic Dataset (HOPV).
